name: sm_debugger
description: "A new Flutter package project."
version: 0.0.1
homepage: https://github.com/shay-wong/flutter_sm_debuger

environment:
  sdk: ">=3.3.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  sm_widget: ^0.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
